// packages/core/src/chat/chat-interface.svelte
<script lang="ts">
  import { getSessionMessageCount } from "@office-agents/sdk";
  import {
    Check,
    ChevronDown,
    Eye,
    EyeOff,
    FolderOpen,
    MessageSquare,
    Moon,
    Plus,
    Settings,
    Sun,
    Trash2,
    Upload,
  } from "lucide-svelte";
  import { onDestroy } from "svelte";
  import type { AppAdapter } from "./app-adapter";
  import { ChatController } from "./chat-controller";
  import { setChatContext } from "./chat-runtime-context";
  import ChatInput from "./chat-input.svelte";
  import FilesPanel from "./files-panel.svelte";
  import MessageList from "./message-list.svelte";
  import SettingsPanel from "./settings-panel.svelte";
  import type { ChatTab } from "./types";

  type Theme = "light" | "dark";

  const THEME_KEY = "office-agents-theme";

  interface Props {
    adapter: AppAdapter;
  }

  let { adapter }: Props = $props();

  const controller = (() => {
    const ctrl = new ChatController(adapter);
    setChatContext(ctrl);
    return ctrl;
  })();

  const runtimeState = controller.state;

  let activeTab = $state<ChatTab>("chat");
  let isDragOver = $state(false);
  let dragCounter = $state(0);
  let sessionDropdownOpen = $state(false);
  let sessionDropdownRef = $state<HTMLDivElement | null>(null);

  let theme = $state<Theme>(loadTheme());

  function loadTheme(): Theme {
    const saved = localStorage.getItem(THEME_KEY) as Theme | null;
    const initial =
      saved ??
      (window.matchMedia("(prefers-color-scheme: light)").matches
        ? "light"
        : "dark");
    document.documentElement.setAttribute("data-theme", initial);
    return initial;
  }

  function toggleTheme() {
    theme = theme === "dark" ? "light" : "dark";
    document.documentElement.setAttribute("data-theme", theme);
    localStorage.setItem(THEME_KEY, theme);
  }

  function formatTokens(value: number): string {
    if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`;
    if (value >= 1_000) return `${(value / 1_000).toFixed(1)}k`;
    return value.toString();
  }

  function formatCost(value: number): string {
    if (value < 0.01) return `$${value.toFixed(4)}`;
    return `$${value.toFixed(3)}`;
  }

  async function handleNewSession() {
    await controller.newSession();
    sessionDropdownOpen = false;
    activeTab = "chat";
  }

  async function handleSwitchSession(sessionId: string) {
    await controller.switchSession(sessionId);
    sessionDropdownOpen = false;
    activeTab = "chat";
  }

  function handleClickOutside(event: MouseEvent) {
    if (
      sessionDropdownRef &&
      event.target instanceof Node &&
      !sessionDropdownRef.contains(event.target)
    ) {
      sessionDropdownOpen = false;
    }
  }

  function handleDragEnter(event: DragEvent) {
    event.preventDefault();
    event.stopPropagation();
    dragCounter += 1;
    if (event.dataTransfer?.types.includes("Files")) {
      isDragOver = true;
    }
  }

  function handleDragLeave(event: DragEvent) {
    event.preventDefault();
    event.stopPropagation();
    dragCounter -= 1;
    if (dragCounter === 0) {
      isDragOver = false;
    }
  }

  function handleDragOver(event: DragEvent) {
    event.preventDefault();
    event.stopPropagation();
  }

  function handleDrop(event: DragEvent) {
    event.preventDefault();
    event.stopPropagation();
    dragCounter = 0;
    isDragOver = false;

    const files = Array.from(event.dataTransfer?.files ?? []);
    if (files.length > 0) {
      void controller.processFiles(files);
    }
  }

  $effect(() => {
    controller.setAdapter(adapter);
  });

  $effect(() => {
    if (!sessionDropdownOpen) return undefined;
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  });

  onDestroy(() => {
    controller.dispose();
  });

  const currentName = $derived(
    $runtimeState.currentSession?.name ?? "New Chat",
  );
  const truncatedName = $derived(
    currentName.length > 20 ? `${currentName.slice(0, 18)}…` : currentName,
  );
  const followMode = $derived($runtimeState.providerConfig?.followMode ?? true);
  const HeaderExtras = $derived(adapter.HeaderExtras);
  const SelectionIndicator = $derived(adapter.SelectionIndicator);
</script>

<div
  role="application"
  class="flex flex-col h-full bg-(--chat-bg) relative"
  style="font-family: var(--chat-font-mono)"
  ondragenter={handleDragEnter}
  ondragleave={handleDragLeave}
  ondragover={handleDragOver}
  ondrop={handleDrop}
>
  <div class="border-b border-(--chat-border) bg-(--chat-bg)">
    <div class="flex items-center justify-between px-2">
      <div class="flex">
        {#if activeTab === "chat"}
          <div class="relative" bind:this={sessionDropdownRef}>
            <button
              type="button"
              onclick={() => (sessionDropdownOpen = !sessionDropdownOpen)}
              class="flex items-center gap-1 px-3 py-2 text-xs uppercase tracking-wider border-b-2 border-(--chat-accent) text-(--chat-text-primary) transition-colors"
              style="font-family: var(--chat-font-mono)"
            >
              <MessageSquare size={12} />
              <span class="max-w-[100px] truncate">{truncatedName}</span>
              <ChevronDown
                size={12}
                class={`transition-transform ${sessionDropdownOpen ? "rotate-180" : ""}`}
              />
            </button>

            {#if sessionDropdownOpen}
              <div
                class="absolute top-full left-0 mt-1 w-56 bg-(--chat-bg) border border-(--chat-border) rounded shadow-lg z-50 overflow-hidden"
              >
                <button
                  type="button"
                  onclick={handleNewSession}
                  disabled={$runtimeState.isStreaming}
                  class={`w-full flex items-center gap-2 px-3 py-2 text-xs transition-colors border-b border-(--chat-border) ${$runtimeState.isStreaming ? "text-(--chat-text-muted) cursor-not-allowed" : "text-(--chat-accent) hover:bg-(--chat-bg-secondary)"}`}
                >
                  <Plus size={14} />
                  New Chat
                </button>

                <div class="max-h-48 overflow-y-auto">
                  {#each $runtimeState.sessions as session (session.id)}
                    {@const isCurrent =
                      session.id === $runtimeState.currentSession?.id}
                    {@const isDisabled =
                      $runtimeState.isStreaming && !isCurrent}
                    <button
                      type="button"
                      disabled={isDisabled}
                      class={`flex items-center justify-between px-3 py-2 text-xs transition-colors w-full text-left ${isCurrent ? "bg-(--chat-bg-secondary)" : ""} ${isDisabled ? "cursor-not-allowed opacity-50" : "cursor-pointer hover:bg-(--chat-bg-secondary)"}`}
                      onclick={() => handleSwitchSession(session.id)}
                    >
                      <div class="flex items-center gap-2 min-w-0 flex-1">
                        {#if isCurrent}
                          <Check
                            size={12}
                            class="text-(--chat-accent) shrink-0"
                          />
                        {:else}
                          <div class="w-3 shrink-0"></div>
                        {/if}
                        <span class="truncate text-(--chat-text-primary)">
                          {session.name}
                        </span>
                      </div>
                      <span
                        class="text-[10px] text-(--chat-text-muted) shrink-0 ml-2"
                      >
                        {getSessionMessageCount(session)}
                      </span>
                    </button>
                  {/each}
                </div>

                {#if $runtimeState.sessions.length > 1 && $runtimeState.currentSession}
                  <button
                    type="button"
                    disabled={$runtimeState.isStreaming}
                    onclick={async (event) => {
                      event.stopPropagation();
                      await controller.deleteCurrentSession();
                      sessionDropdownOpen = false;
                    }}
                    class={`w-full flex items-center gap-2 px-3 py-2 text-xs transition-colors border-t border-(--chat-border) ${$runtimeState.isStreaming ? "text-(--chat-text-muted) cursor-not-allowed" : "text-(--chat-error) hover:bg-(--chat-bg-secondary)"}`}
                  >
                    <Trash2 size={14} />
                    Delete Current Session
                  </button>
                {/if}
              </div>
            {/if}
          </div>
        {:else}
          <button
            type="button"
            onclick={() => (activeTab = "chat")}
            class="flex items-center gap-1.5 px-3 py-2 text-xs uppercase tracking-wider border-b-2 border-transparent transition-colors text-(--chat-text-muted) hover:text-(--chat-text-secondary)"
            style="font-family: var(--chat-font-mono)"
          >
            <MessageSquare size={12} />
            Chat
          </button>
        {/if}

        <button
          type="button"
          onclick={() => (activeTab = "files")}
          class={`flex items-center gap-1.5 px-3 py-2 text-xs uppercase tracking-wider border-b-2 transition-colors ${activeTab === "files" ? "border-(--chat-accent) text-(--chat-text-primary)" : "border-transparent text-(--chat-text-muted) hover:text-(--chat-text-secondary)"}`}
          style="font-family: var(--chat-font-mono)"
        >
          <FolderOpen size={12} />
          Files
        </button>

        <button
          type="button"
          onclick={() => (activeTab = "settings")}
          class={`flex items-center gap-1.5 px-3 py-2 text-xs uppercase tracking-wider border-b-2 transition-colors ${activeTab === "settings" ? "border-(--chat-accent) text-(--chat-text-primary)" : "border-transparent text-(--chat-text-muted) hover:text-(--chat-text-secondary)"}`}
          style="font-family: var(--chat-font-mono)"
        >
          <Settings size={12} />
          Settings
        </button>
      </div>

      <div class="flex items-center">
        {#if activeTab === "chat" && HeaderExtras}
          <HeaderExtras />
        {/if}

        {#if activeTab === "chat" && (adapter.showFollowModeToggle ?? true)}
          <button
            type="button"
            onclick={() => controller.toggleFollowMode()}
            class={`p-1.5 transition-colors ${followMode ? "text-(--chat-accent) hover:text-(--chat-text-primary)" : "text-(--chat-text-muted) hover:text-(--chat-text-primary)"}`}
            data-tooltip={followMode ? "Follow mode: ON" : "Follow mode: OFF"}
          >
            {#if followMode}
              <Eye size={14} />
            {:else}
              <EyeOff size={14} />
            {/if}
          </button>
        {/if}

        <button
          type="button"
          onclick={toggleTheme}
          class="p-1.5 text-(--chat-text-muted) hover:text-(--chat-text-primary) transition-colors"
          data-tooltip={theme === "dark" ? "Light mode" : "Dark mode"}
        >
          {#if theme === "dark"}
            <Sun size={14} />
          {:else}
            <Moon size={14} />
          {/if}
        </button>

        {#if activeTab === "chat" && $runtimeState.messages.length > 0}
          <button
            type="button"
            onclick={() => controller.clearMessages()}
            class="p-1.5 text-(--chat-text-muted) hover:text-(--chat-error) transition-colors"
            data-tooltip="Clear messages"
          >
            <Trash2 size={14} />
          </button>
        {/if}
      </div>
    </div>
  </div>

  {#if activeTab === "chat"}
    <MessageList />
    {#if SelectionIndicator}
      <SelectionIndicator />
    {/if}
    <ChatInput />
    {#if $runtimeState.providerConfig}
      <div
        class="flex items-center justify-between px-3 py-1.5 text-[10px] border-t border-(--chat-border) bg-(--chat-bg-secondary) text-(--chat-text-muted)"
        style="font-family: var(--chat-font-mono)"
      >
        <div class="flex items-center gap-3">
          <span title="Input tokens">
            ↑{formatTokens($runtimeState.sessionStats.inputTokens)}
          </span>
          <span title="Output tokens">
            ↓{formatTokens($runtimeState.sessionStats.outputTokens)}
          </span>
          {#if $runtimeState.sessionStats.cacheRead > 0}
            <span title="Cache read tokens">
              R{formatTokens($runtimeState.sessionStats.cacheRead)}
            </span>
          {/if}
          {#if $runtimeState.sessionStats.cacheWrite > 0}
            <span title="Cache write tokens">
              W{formatTokens($runtimeState.sessionStats.cacheWrite)}
            </span>
          {/if}
          <span title="Total cost">
            {formatCost($runtimeState.sessionStats.totalCost)}
          </span>
          {#if $runtimeState.sessionStats.contextWindow > 0}
            <span title="Context usage">
              {(
                (($runtimeState.sessionStats.lastInputTokens || 0) /
                  $runtimeState.sessionStats.contextWindow) *
                100
              ).toFixed(1)}%/{formatTokens(
                $runtimeState.sessionStats.contextWindow,
              )}
            </span>
          {/if}
        </div>
        <div class="flex items-center gap-1">
          <span>{$runtimeState.providerConfig.provider}</span>
          <span class="text-(--chat-text-secondary)">
            {$runtimeState.providerConfig.model}
          </span>
          {#if $runtimeState.providerConfig.thinking !== "none"}
            <span class="text-(--chat-accent)">
              • {$runtimeState.providerConfig.thinking}
            </span>
          {/if}
        </div>
      </div>
    {/if}
  {:else if activeTab === "files"}
    <FilesPanel />
  {:else}
    <SettingsPanel />
  {/if}

  {#if isDragOver}
    <div
      class="absolute inset-0 z-50 flex items-center justify-center bg-(--chat-bg)/80 backdrop-blur-sm"
    >
      <div
        class="flex flex-col items-center gap-3 p-8 border-2 border-dashed border-(--chat-accent) rounded-lg"
      >
        <Upload size={32} class="text-(--chat-accent)" />
        <span class="text-sm text-(--chat-text-primary)">Drop files here</span>
      </div>
    </div>
  {/if}
</div>

// packages/core/src/chat/chat-interface.tsx
import { getSessionMessageCount } from "@office-agents/sdk";
import {
  Check,
  ChevronDown,
  Eye,
  EyeOff,
  MessageSquare,
  Moon,
  Plus,
  Settings,
  Sun,
  Trash2,
  Upload,
} from "lucide-react";
import {
  type DragEvent,
  type ReactNode,
  useCallback,
  useEffect,
  useRef,
  useState,
} from "react";
import type { AppAdapter } from "./app-adapter";
import { ChatProvider, useChat } from "./chat-context";
import { ChatInput } from "./chat-input";
import { MessageList } from "./message-list";
import { SettingsPanel } from "./settings-panel";
import type { ChatTab } from "./types";

type Theme = "light" | "dark";
const THEME_KEY = "office-agents-theme";

function useTheme() {
  const [theme, setTheme] = useState<Theme>(() => {
    const saved = localStorage.getItem(THEME_KEY) as Theme | null;
    const initial =
      saved ??
      (window.matchMedia("(prefers-color-scheme: light)").matches
        ? "light"
        : "dark");
    document.documentElement.setAttribute("data-theme", initial);
    return initial;
  });

  const toggle = () => {
    const next = theme === "dark" ? "light" : "dark";
    document.documentElement.setAttribute("data-theme", next);
    localStorage.setItem(THEME_KEY, next);
    setTheme(next);
  };

  return { theme, toggle };
}

function formatTokens(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}k`;
  return n.toString();
}

function formatCost(n: number): string {
  if (n < 0.01) return `$${n.toFixed(4)}`;
  return `$${n.toFixed(3)}`;
}

function StatsBar() {
  const { state } = useChat();
  const { sessionStats, providerConfig } = state;

  if (!providerConfig) return null;

  const contextPct =
    sessionStats.contextWindow > 0 && sessionStats.lastInputTokens > 0
      ? (
          (sessionStats.lastInputTokens / sessionStats.contextWindow) *
          100
        ).toFixed(1)
      : "0";

  return (
    <div
      className="flex items-center justify-between px-3 py-1.5 text-[10px] border-t border-(--chat-border) bg-(--chat-bg-secondary) text-(--chat-text-muted)"
      style={{ fontFamily: "var(--chat-font-mono)" }}
    >
      <div className="flex items-center gap-3">
        <span title="Input tokens">
          ↑{formatTokens(sessionStats.inputTokens)}
        </span>
        <span title="Output tokens">
          ↓{formatTokens(sessionStats.outputTokens)}
        </span>
        {sessionStats.cacheRead > 0 && (
          <span title="Cache read tokens">
            R{formatTokens(sessionStats.cacheRead)}
          </span>
        )}
        {sessionStats.cacheWrite > 0 && (
          <span title="Cache write tokens">
            W{formatTokens(sessionStats.cacheWrite)}
          </span>
        )}
        <span title="Total cost">{formatCost(sessionStats.totalCost)}</span>
        {sessionStats.contextWindow > 0 && (
          <span title="Context usage">
            {contextPct}%/{formatTokens(sessionStats.contextWindow)}
          </span>
        )}
      </div>
      <div className="flex items-center gap-1">
        <span>{providerConfig.provider}</span>
        <span className="text-(--chat-text-secondary)">
          {providerConfig.model}
        </span>
        {providerConfig.thinking !== "none" && (
          <span className="text-(--chat-accent)">
            • {providerConfig.thinking}
          </span>
        )}
      </div>
    </div>
  );
}

function TabButton({
  active,
  onClick,
  children,
}: {
  active: boolean;
  onClick: () => void;
  children: ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`
        flex items-center gap-1.5 px-3 py-2 text-xs uppercase tracking-wider
        border-b-2 transition-colors
        ${
          active
            ? "border-(--chat-accent) text-(--chat-text-primary)"
            : "border-transparent text-(--chat-text-muted) hover:text-(--chat-text-secondary)"
        }
      `}
      style={{ fontFamily: "var(--chat-font-mono)" }}
    >
      {children}
    </button>
  );
}

function SessionDropdown({ onSelect }: { onSelect: () => void }) {
  const { state, newSession, switchSession, deleteCurrentSession } = useChat();
  const [open, setOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const isStreaming = state.isStreaming;

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (
        dropdownRef.current &&
        !dropdownRef.current.contains(e.target as Node)
      ) {
        setOpen(false);
      }
    };
    if (open) document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [open]);

  const currentName = state.currentSession?.name ?? "New Chat";
  const truncatedName =
    currentName.length > 20 ? `${currentName.slice(0, 18)}…` : currentName;

  const handleNewSession = async () => {
    console.log("[UI] handleNewSession clicked");
    await newSession();
    console.log("[UI] newSession completed");
    setOpen(false);
    onSelect();
  };

  const handleSwitch = async (id: string) => {
    await switchSession(id);
    setOpen(false);
    onSelect();
  };

  return (
    <div className="relative" ref={dropdownRef}>
      <button
        type="button"
        onClick={() => setOpen(!open)}
        className={`
          flex items-center gap-1 px-3 py-2 text-xs uppercase tracking-wider
          border-b-2 border-(--chat-accent) text-(--chat-text-primary) transition-colors
        `}
        style={{ fontFamily: "var(--chat-font-mono)" }}
      >
        <MessageSquare size={12} />
        <span className="max-w-[100px] truncate">{truncatedName}</span>
        <ChevronDown
          size={12}
          className={`transition-transform ${open ? "rotate-180" : ""}`}
        />
      </button>

      {open && (
        <div
          className="absolute top-full left-0 mt-1 w-56 bg-(--chat-bg) border border-(--chat-border) rounded shadow-lg z-50 overflow-hidden"
          style={{ fontFamily: "var(--chat-font-mono)" }}
        >
          <button
            type="button"
            onClick={handleNewSession}
            disabled={isStreaming}
            className={`w-full flex items-center gap-2 px-3 py-2 text-xs transition-colors border-b border-(--chat-border) ${
              isStreaming
                ? "text-(--chat-text-muted) cursor-not-allowed"
                : "text-(--chat-accent) hover:bg-(--chat-bg-secondary)"
            }`}
          >
            <Plus size={14} />
            New Chat
          </button>

          <div className="max-h-48 overflow-y-auto">
            {state.sessions.map((session) => {
              const isCurrent = session.id === state.currentSession?.id;
              const isDisabled = isStreaming && !isCurrent;
              return (
                <button
                  type="button"
                  key={session.id}
                  disabled={isDisabled}
                  className={`
                    flex items-center justify-between px-3 py-2 text-xs transition-colors w-full text-left
                    ${isCurrent ? "bg-(--chat-bg-secondary)" : ""}
                    ${isDisabled ? "cursor-not-allowed opacity-50" : "cursor-pointer hover:bg-(--chat-bg-secondary)"}
                  `}
                  onClick={() => handleSwitch(session.id)}
                >
                  <div className="flex items-center gap-2 min-w-0 flex-1">
                    {session.id === state.currentSession?.id ? (
                      <Check
                        size={12}
                        className="text-(--chat-accent) shrink-0"
                      />
                    ) : (
                      <div className="w-3 shrink-0" />
                    )}
                    <span className="truncate text-(--chat-text-primary)">
                      {session.name}
                    </span>
                  </div>
                  <span className="text-[10px] text-(--chat-text-muted) shrink-0 ml-2">
                    {getSessionMessageCount(session)}
                  </span>
                </button>
              );
            })}
          </div>

          {state.sessions.length > 1 && state.currentSession && (
            <button
              type="button"
              disabled={isStreaming}
              onClick={async (e) => {
                e.stopPropagation();
                await deleteCurrentSession();
                setOpen(false);
              }}
              className={`w-full flex items-center gap-2 px-3 py-2 text-xs transition-colors border-t border-(--chat-border) ${
                isStreaming
                  ? "text-(--chat-text-muted) cursor-not-allowed"
                  : "text-(--chat-error) hover:bg-(--chat-bg-secondary)"
              }`}
            >
              <Trash2 size={14} />
              Delete Current Session
            </button>
          )}
        </div>
      )}
    </div>
  );
}

function ChatHeader({
  activeTab,
  onTabChange,
  theme,
  onThemeToggle,
}: {
  activeTab: ChatTab;
  onTabChange: (tab: ChatTab) => void;
  theme: Theme;
  onThemeToggle: () => void;
}) {
  const { adapter, clearMessages, state, toggleFollowMode } = useChat();
  const followMode = state.providerConfig?.followMode ?? true;
  const HeaderExtras = adapter.HeaderExtras;
  const showFollowModeToggle = adapter.showFollowModeToggle ?? true;

  return (
    <div className="border-b border-(--chat-border) bg-(--chat-bg)">
      <div className="flex items-center justify-between px-2">
        <div className="flex">
          {activeTab === "chat" ? (
            <SessionDropdown onSelect={() => onTabChange("chat")} />
          ) : (
            <TabButton active={false} onClick={() => onTabChange("chat")}>
              <MessageSquare size={12} />
              Chat
            </TabButton>
          )}
          <TabButton
            active={activeTab === "settings"}
            onClick={() => onTabChange("settings")}
          >
            <Settings size={12} />
            Settings
          </TabButton>
        </div>
        <div className="flex items-center">
          {activeTab === "chat" && HeaderExtras && <HeaderExtras />}
          {activeTab === "chat" && showFollowModeToggle && (
            <button
              type="button"
              onClick={toggleFollowMode}
              className={`p-1.5 transition-colors ${
                followMode
                  ? "text-(--chat-accent) hover:text-(--chat-text-primary)"
                  : "text-(--chat-text-muted) hover:text-(--chat-text-primary)"
              }`}
              data-tooltip={followMode ? "Follow mode: ON" : "Follow mode: OFF"}
            >
              {followMode ? <Eye size={14} /> : <EyeOff size={14} />}
            </button>
          )}
          <button
            type="button"
            onClick={onThemeToggle}
            className="p-1.5 text-(--chat-text-muted) hover:text-(--chat-text-primary) transition-colors"
            data-tooltip={theme === "dark" ? "Light mode" : "Dark mode"}
          >
            {theme === "dark" ? <Sun size={14} /> : <Moon size={14} />}
          </button>
          {activeTab === "chat" && state.messages.length > 0 && (
            <button
              type="button"
              onClick={clearMessages}
              className="p-1.5 text-(--chat-text-muted) hover:text-(--chat-error) transition-colors"
              data-tooltip="Clear messages"
            >
              <Trash2 size={14} />
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

function SelectionIndicatorSlot() {
  const { adapter } = useChat();
  if (!adapter.SelectionIndicator) return null;
  return <adapter.SelectionIndicator />;
}

function ChatContent() {
  const [activeTab, setActiveTab] = useState<ChatTab>("chat");
  const { theme, toggle } = useTheme();
  const { processFiles } = useChat();
  const [isDragOver, setIsDragOver] = useState(false);
  const dragCounterRef = useRef(0);

  const handleDragEnter = useCallback((e: DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    dragCounterRef.current++;
    if (e.dataTransfer.types.includes("Files")) {
      setIsDragOver(true);
    }
  }, []);

  const handleDragLeave = useCallback((e: DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    dragCounterRef.current--;
    if (dragCounterRef.current === 0) {
      setIsDragOver(false);
    }
  }, []);

  const handleDragOver = useCallback((e: DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
  }, []);

  const handleDrop = useCallback(
    (e: DragEvent) => {
      e.preventDefault();
      e.stopPropagation();
      dragCounterRef.current = 0;
      setIsDragOver(false);
      const files = Array.from(e.dataTransfer.files);
      if (files.length > 0) {
        processFiles(files);
      }
    },
    [processFiles],
  );

  return (
    <div
      role="application"
      className="flex flex-col h-full bg-(--chat-bg) relative"
      style={{ fontFamily: "var(--chat-font-mono)" }}
      onDragEnter={handleDragEnter}
      onDragLeave={handleDragLeave}
      onDragOver={handleDragOver}
      onDrop={handleDrop}
    >
      <ChatHeader
        activeTab={activeTab}
        onTabChange={setActiveTab}
        theme={theme}
        onThemeToggle={toggle}
      />
      {activeTab === "chat" ? (
        <>
          <MessageList />
          <SelectionIndicatorSlot />
          <ChatInput />
          <StatsBar />
        </>
      ) : (
        <SettingsPanel />
      )}

      {/* Drag-and-drop overlay */}
      {isDragOver && (
        <div className="absolute inset-0 z-50 flex items-center justify-center bg-(--chat-bg)/80 backdrop-blur-sm">
          <div className="flex flex-col items-center gap-3 p-8 border-2 border-dashed border-(--chat-accent) rounded-lg">
            <Upload size={32} className="text-(--chat-accent)" />
            <span className="text-sm text-(--chat-text-primary)">
              Drop files here
            </span>
          </div>
        </div>
      )}
    </div>
  );
}

export function ChatInterface({ adapter }: { adapter: AppAdapter }) {
  return (
    <ChatProvider adapter={adapter}>
      <ChatContent />
    </ChatProvider>
  );
}
